stages:
  load_data:
    cmd: python src/load_data.py
    deps:
    - src/load_data.py
    params:
    - train.batch_size
    - train.dropout
    - train.hidden_units
    - train.lr
    - train.num_epochs
    outs:
    - output/data.pkl
